import { StyleSheet } from "react-native";
import { mobileTheme as theme } from "./mobileTheme";

export const feedStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: theme.colors.surfaceMuted },
  container: { flex: 1 },
  scrollContent: { padding: theme.spacing.lg, gap: theme.spacing.lg, paddingBottom: 120 },
  topBar: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  pageTitle: { color: theme.colors.ink, fontSize: 28, fontWeight: "800" },
  heroCard: { borderRadius: theme.radius.lg, padding: theme.spacing.xl, backgroundColor: theme.colors.primaryDeep },
  heroIconWrap: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: "rgba(255,255,255,0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: theme.spacing.md,
  },
  heroTitle: { color: theme.colors.surface, fontSize: 28, fontWeight: "800", marginBottom: theme.spacing.xs },
  heroText: { color: "#e7f4fb", lineHeight: 23, fontSize: 14, marginBottom: theme.spacing.lg },
  heroButton: {
    alignSelf: "flex-start",
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.pill,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  heroButtonText: { color: theme.colors.primaryDeep, fontWeight: "800" },
  sectionHeader: { gap: 4 },
  sectionTitle: { color: theme.colors.ink, fontSize: 22, fontWeight: "700" },
  sectionText: { color: theme.colors.inkMuted, fontSize: 14 },
  animalCard: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.lg, padding: theme.spacing.md, shadowColor: "#000", shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 3, gap: theme.spacing.sm },
  animalImage: { width: "100%", height: 180, borderRadius: theme.radius.md, backgroundColor: theme.colors.primarySoft },
  badge: { alignSelf: "flex-start", backgroundColor: theme.colors.primarySoft, borderRadius: theme.radius.pill, paddingHorizontal: 10, paddingVertical: 6 },
  badgeText: { color: theme.colors.primary, fontWeight: "700", fontSize: 11, textTransform: "uppercase" },
  cardTitle: { color: theme.colors.ink, fontSize: 18, fontWeight: "700" },
  cardText: { color: theme.colors.inkMuted, lineHeight: 21 },
  postCard: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.lg, padding: theme.spacing.md, gap: theme.spacing.sm, shadowColor: "#000", shadowOpacity: 0.08, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 3 },
  postTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  sponsorButton: {
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.primarySoft,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  sponsorButtonText: { color: theme.colors.primaryDeep, fontWeight: "700", fontSize: 12 },
  orgChip: { backgroundColor: theme.colors.primarySoft, borderRadius: theme.radius.pill, paddingHorizontal: 10, paddingVertical: 6 },
  orgChipText: { color: theme.colors.primary, fontWeight: "700", fontSize: 12 },
  linkText: { color: theme.colors.primaryDeep, fontWeight: "700", fontSize: 14 },
  metaText: { color: theme.colors.inkMuted, fontSize: 13 },
  postImage: { width: "100%", height: 220, borderRadius: theme.radius.md, backgroundColor: theme.colors.primarySoft },
  emptyCard: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.lg, padding: theme.spacing.xl },
  emptyText: { color: theme.colors.inkMuted, textAlign: "center", lineHeight: 22 },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(9,24,34,0.55)", justifyContent: "center", padding: theme.spacing.lg },
  modalCard: { backgroundColor: theme.colors.surface, borderRadius: theme.radius.lg, padding: theme.spacing.xl, gap: theme.spacing.md },
  modalEyebrow: { color: theme.colors.inkMuted, textTransform: "uppercase", fontWeight: "700", fontSize: 12, letterSpacing: 1 },
  modalTitle: { color: theme.colors.ink, fontSize: 22, fontWeight: "800" },
  modalText: { color: theme.colors.inkSoft, lineHeight: 23 },
  modalClose: { alignSelf: "flex-end", backgroundColor: theme.colors.primary, borderRadius: theme.radius.pill, paddingHorizontal: 18, paddingVertical: 10 },
  modalCloseText: { color: theme.colors.surface, fontWeight: "700" },
});
