import Svg, { Ellipse, Path } from "react-native-svg";

// PLACEHOLDER LOGO generated by Stitch. The professional logo will replace it.
// Every screen draws the logo through this component, so swapping the artwork here
// updates the whole app.

type Props = {
  size?: number;
  color?: string;
};

export default function LogoMark({ size = 80, color = "#FFFFFF" }: Props) {
  return (
    <Svg width={size} height={size} viewBox="0 0 72 72" fill="none" accessibilityLabel="StrayAid logo">
      <Path
        d="M36 63.5C36 63.5 10 47.8 10 27.5C10 18.2 17.5 10.7 26.8 10.7C31.5 10.7 35.8 12.6 36 12.8C36.2 12.6 40.5 10.7 45.2 10.7C54.5 10.7 62 18.2 62 27.5C62 47.8 36 63.5 36 63.5Z"
        stroke={color}
        strokeWidth={4.5}
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <Ellipse cx={36} cy={38} rx={7.5} ry={6.5} fill={color} />
      <Ellipse cx={27} cy={27} rx={3.5} ry={4.5} fill={color} transform="rotate(-15 27 27)" />
      <Ellipse cx={45} cy={27} rx={3.5} ry={4.5} fill={color} transform="rotate(15 45 27)" />
      <Ellipse cx={20.5} cy={35} rx={3} ry={4} fill={color} transform="rotate(-30 20.5 35)" />
      <Ellipse cx={51.5} cy={35} rx={3} ry={4} fill={color} transform="rotate(30 51.5 35)" />
    </Svg>
  );
}
