# Generated by Django 5.2.11 on 2026-09-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_adopted_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='microchip_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
