# Generated by Django 5.2.11 on 2026-10-05 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_microchip_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='health',
            field=models.CharField(blank=True, choices=[('healthy', 'Healthy'), ('minor_issues', 'Minor issues'), ('under_treatment', 'Under treatment'), ('special_needs', 'Special needs')], max_length=20),
        ),
        migrations.AddField(
            model_name='animal',
            name='vaccinated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('home_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('other', 'Other')], max_length=20)),
                ('has_other_pets', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to='animals.animal')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pkr', models.PositiveIntegerField()),
                ('monthly', models.BooleanField(default=False)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='animals.animal')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
