# Generated by Django 5.2.11 on 2026-09-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('medical', 'Medical Recovery'), ('adoption', 'Adoption Ready'), ('sponsorship', 'Sponsorship Goal'), ('foster', 'Foster Found')], max_length=30),
        ),
    ]
