# Generated by Django 5.2.11 on 2026-09-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payment_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
