# Generated by Django 5.2.11 on 2026-03-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='latitiude',
            new_name='latitude',
        ),
    ]
