# Generated by Django 5.2.11 on 2026-10-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0004_case_area_case_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notify_reporter',
            field=models.BooleanField(default=True),
        ),
    ]
