# Generated by Django 5.2.11 on 2026-10-05 07:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0005_report_notify_reporter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('rescued', 'Rescued'), ('closed', 'Closed'), ('adoption', 'Up For Adoption')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_updates', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='rescue.case')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
